export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FATCH_INGREDIENT = 'FATCH_INGREDIENT';
export const FATCH_FAILD = 'FATCH_FAILD';

export const BURGER_CHECKOUT_SUCCESS = 'BURGER_CHECKOUT_SUCCESS';
export const BURGER_CHECKOUT_FAILD = 'BURGER_CHECKOUT_FAILD';

export const FATCH_ORDER_SUCCESS = 'FATCH_ORDER_SUCCESS';
export const FATCH_ORDER_FAILD = 'FATCH_ORDER_FAILD';

export const AUTH_FAILD = 'AUTH_FAILD';
export const AUTH_USER = 'AUTH_USER';
export const LOG_OUT = 'LOG_OUT';
export const AUTH_REDIRECT = 'AUTH_REDIRECT'

export const CANCLE_BUTTON = 'CANCLE_BUTTON';
