export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const FATCH_INGREDIENT = 'FATCH_INGREDIENT'
export const FATCH_FAILD = 'FATCH_FAILD'

export const BURGER_CHECKOUT_SUCCESS = 'BURGER_CHECKOUT_SUCCESS';
export const BURGER_CHECKOUT_FIELD = 'BURGER_CHECKOUT_FIELD';

export const  FATCH_ORDER_SUCCESS = 'FATCH_ORDER_SUCCESS'
export const FATCH_ORDER_FAILD = 'FATCH_ORDER_FAILD'
